### ISSUE TITLE
cfg_tl.py  Character_Data_Class.y_posi incorrect address

### ISSUE THREAD

**Issue by rkaganda** [kosunan/MBTL_Training#2]
https://github.com/kosunan/MBTL_Training/blob/98bed73ad95e1ccc2d1ae414f0bbabd0096b3b36/src/cfg_tl.py#L69

self.y_posi = pack(list, self.x_posi.ad + 4 + size, 4)  
wrong address?
self.x_posi.ad = 0x64 + size 

self.y_posi = pack(list, self.x_posi.ad + 4, 4)
correct
because size offset already added to self.x_posi.ad
from call
self.x_posi = pack(list, 0x64 + size, 4)
pack(list, addres, len)

thank you for all your hard work on this project, it has been very helpful

**Comment by kosunan** [comment]
Thank you very much.
I see my mistake.
